- .gitignore
- src/scripts/concat.sh
The goal here is to be able to build this on Windows or Linux.  For
now the easiest thing seems to have both a bash and powershell scripts
for the same thing.
I have also created a `.gitignore` file and added the `public-db.sql`
artifact to it's ignore to prevent it from being committed into git
by mistake.
> Create Bash Concat for Linux & Update .gitignore

- src/data/SpecXAbility.sql
adds missing ability in 'specxability' for minstrels to wield instruments
> minstrel instru

- .travis.yml
Just a simple CI test to ensure that you can dump the generated SQL script to a MySQL Database.
> Add Travis CI Test

- .gitignore
- src/scripts/concat.go
- src/scripts/config.example.yml
- src/scripts/export_to_json.go
Start of new GO scripts. these will be used to convert the database into json and for converting the json back into insert statements in the concat. The goal is to separate out the stored data from its mysql implementation. This should make merge conflicts easier.
> New go scripts

- src/data/.gitattributes
- src/scripts/export_to_json.go
Change git to use LF instead of CRLF for the data directory.
Only replace the json data if it is modified.
> Correct Line Endings Issue

- src/schema/Account.sql
- src/schema/Battleground.sql
A couple table files ended in ;;, this was breaking MariaDB
> Fix schema files for MariaDB

- src/data/Path.json
- Should be final fix on Classic Hib Horse Routes, need issues open on any other issues
- First batch of Albion horse route fixes: 
-- Cotswold Village
-- Nobs Farm
-- Castle Sauvage
-- Camelot North Gate
> Horse routes 3

- src/data/Path.json
- Added merchants where necessary
- Fixed all Ticket names
- Added or corrected all horse routes
> Albion Classic and SI Horse Route Fixes

- src/data/Path.json
- Fixed Classic Horse Routes and Merchants
- Added SI Horse routes
- Added Horses to merchants for Taxi model where necessary
- Updated Horse NPCTemplate on those that were modeled after Alb
- Fixed NPCTemplates for Stable Merchants in Aegirhamm, Dyrfjell, and Knarr
> MIdgard Horse Routes

- src/data/LootTemplate.json
- src/data/MobXLootTemplate.json
- Inquisitors Almost complete
- Legion Added
- Most of the Earls
- Most of the Dukes
- Princes and Princess added 
- Chamberlain added
- High Lords added
- Add Missing NPCTemplates
- Updated Models and equiptemplates for High Lord Oro and other mobs
- Mob cleanup around Hib Starting area
> DF Mob Improvements

- src/data/LootTemplate.json
From @Nachtmahr91:
- Final set of updates to Camelot Hills
- Fixed NPCTemplates
- Added some missing mobs
- Fixed Loot tables
- Fixed Items with wrong stats
> Npc updates

- src/data/LootTemplate.json
- src/data/MobXLootTemplate.json
Closes issues #112 
Part of #116
> Npc updates2

- src/data/LootTemplate.json
- src/data/MobXLootTemplate.json
- src/data/Path.json
- Mob Name corrections
- Mob Loot table updates
- Mob population fixes
- Diamond Seal Merchant Fixes
- Diamond Seal Items fixes
- Fixed Pricing
- Fixed Procs
- Fixed Stats
- Fixed Charges
- Fixed Levels
- Added some visuals
> Df updates

- src/data/LootTemplate.json
- Black Mountains South Mob and NPC fixes from @Nachtmahr91
> Fixes for #116

- src/data/LootTemplate.json
- src/data/MobXLootTemplate.json
- Lynn Barfog fixes
- LootTemplate fixes (Started with "a" mobs in classic zones
- Fixing LootTemplateName / Mob Names in Loottables - Should match mob name exactly
- Adding missing items in loot templates
- Fixing mob names  (Started with "a" mobs in classic zones)
- If regular mob, lower casing it
- Fixing NPCTemplates 
- Proper Body Type / Resists Type Etc.
- Fixing ItemTemplates where stats are wrong, or incorrect
- Fixing Id_nb in itematemplate table as well.
> NPC_Updates

- src/data/LootTemplate.json
- src/data/MobXLootTemplate.json
- Black Mountains North (THX @Nachtmahr91!)
- All classic mobs start with "A" should be fixed (Mid/Hib/Alb)
- Loot Tables updated
- Items fixed with the correct stats
> NPCTemplate / LootTemplate / ItemTemplate Fixes

- src/data/LootTemplate.json
- Deleted Loot from Ellyls, which does not belong in their LootTemplate.
- Added loot from Ellyls, which was missing.
- Changes in the NPC template of Ellyls.
> ellyl fixes

- src/data/LootTemplate.json
I added two missing NPCs in Camelot Hills.
Furthermore, I corrected a few mobs in Lyonesse including their loot template and fixed the items.
> Camleot Hills fix and Lyonesse fix

- src/customizations/PveKeeps.sql
Rather than leaving all keeps at level 4, set them to different levels to match Gaheris
> Changed PvE Keep Levels

- src/customizations/ServerType.PVE.DreadedSeals.sql
Adds a loot generator entry for the labyrinth region, and adds loot template dreaded seal entries for epic dungeon bosses and dragons
> Add more dreaded seal drops

- src/data/LootTemplate.json
I corrected the NPC template in four mobs and added a few items to the LootTemplate and corrected items.
> Test and Lyonesse Fixes

- src/data/Path.json
- src/data/WorldObject.json
Tried to Match live as much as possible
* move NPC's where they should be, removed extra ones
* reduced the number of mobs around Mag Mell (Was extremely dense)
* Added campfire with badgers that exists outside of Mag Mell along the road
> Magmell improvements

- src/data/LootTemplate.json
I corrected the rest of the stuff in Llyn Barfog and started to set up the merchants and fill them with items like on the live server at Castle Sauvage.
> Llyn Barfog corrected mobs and Castle Sauvage Merchants / Items (Live Like)

- src/data/Regions.json
Fixes benign WeatherManager errors
> Remove Regions without zones

- .github/workflows/build_queries.yml
- README.md
- concat.go
- export_to_json.go
- go.mod
- go.sum
- main.go
Combine concat.go and export_to_json.go to one program via flags
Split test and release workflow
> Update Go to 1.17

- README.md
- concat.go
Remove step from Contributing
Make build instruction a bit more concise
> Create config.yml if it does not exist

- data/Keep.json
- data/KeepPosition.json
The Hills of Claret is now available : 
- Central keep : addition of Lord and guards
- For each realm keep (Albion/Midgard/Hibernia), addition of : 
-- Guards
-- Teleporter
-- Siegemaster merchant (mini ram, catapult, ballista, trebuchet)
-- Healer
-- Hastener
-- Other NPC for further usages (quests, realm enhancement, ...)
- Mobs added in the region 
- EquipmentTemplate added for some NPC
Notes : 
- Mini ram and catapult are fully working while ballista and trebuchet will need some fixes
- Dataquest will be added on a later stage (XP and gold quest)
> Activation of Hills of Claret battleground (10-14)

- config/config.example.yml
- data/SpellXCustomValues.json
Remove SpellXCustomValues from export ignore
> Add missing spell chains for SpellTokenMerchant

- data/Battleground.json
- data/Keep.json
Fix keeps position
Add lords and guards in the central keep
Add teleporter, guards, merchant in each realm keep 
Add battleground in the battleground list
To come : fix door in each realm keep and add weapons/armor/jewel to merchant in each realm
> Killaloe BG : activate battleground

- data/KeepPosition.json
Add dummy NPCTemplates for missing ones
Fix NPCEquipmentTemplate errors
Remove empty equipment templates from mobs
Fix not loading KeepDoors
> Fix DOLServer errors/warnings

- .github/workflows/release.yml
Import previously complained if gcc was absent
Update deprecated actions
> Fix windows builds

- data/KeepPosition.json
Doors will now work as expected
> Killaloe BG : add 5 doors in the central keep

- data/SpecXAbility.json
- data/Specialization.json
This was previously hardcoded in the server
> Add OldArchery

- customizations/UpdatedSpecMultipliers.sql
Replace was clobbering a bunch of class data, leading to null exceptions.
> Fix clobbering CharacterClass data

- data/StartupLocation.json
Review StartupLocation and mob/npctemplate to start Tutorial quests (alb/mid/hib)
> Initial work for Tutorial quests

- data/WorldObject.json
Init mob and worldobject for mid tutorial quest
> Mid tutorial quest 

- .github/workflows/test.yml
- src/tools/export.go
SQLite 2.41 and above does not accept double-quoted strings
Add check to make sure data is not changed on export->import
> Fix exported sql to be compatible with SQLite 3.41+

- data/WorldObject.json
Add NPC and worldobject for Hibernia tutorial quests
> Add NPC and worldobject for Hibernia tutorial quests
